/**
 * verification.ts — Cross-Model Verification Pass
 *
 * From the spec: "The Reasoning Core audits the code generated by Kimi 
 * for logical vulnerabilities."
 *
 * Here: the reasoning expert reviews all outputs for correctness,
 * consistency, and logical coherence before synthesis.
 * Only runs if there are 2+ sub-tasks or a code task is present.
 */

import { complete } from './hf';
import { EXPERT_MODELS } from '../types/orchestrator';
import type { SubTask } from '../types/orchestrator';

const VERIFICATION_SYSTEM = `You are the Verification Auditor — the cross-model quality gate in a 
Mixture-of-Agents pipeline.

You receive outputs from multiple specialist AI models (reasoning, code, conversational, scientific).
Your job is to audit them for:
1. Logical consistency — do the outputs contradict each other?
2. Correctness — are there factual errors, buggy code, or invalid reasoning?
3. Completeness — are there gaps that weren't addressed?
4. Coherence — will these outputs combine cleanly into a single response?

Be terse. Flag real issues only. Format:
- If everything is acceptable: "VERIFIED: All outputs are consistent and correct."
- If issues found: list each issue as "ISSUE [role]: <description>" then "RECOMMENDATION: <fix>"
- Max 200 words.`;

export async function verify(subTasks: SubTask[]): Promise<string> {
  // Skip verification for single simple tasks
  const completedTasks = subTasks.filter(t => t.status === 'done' && t.output);
  if (completedTasks.length <= 1) {
    return 'VERIFIED: Single-task response, no cross-model verification needed.';
  }

  const summary = completedTasks
    .map(t => `[${t.role.toUpperCase()} — ${t.model.split('/')[1]}]\n${t.output.slice(0, 600)}${t.output.length > 600 ? '…' : ''}`)
    .join('\n\n---\n\n');

  try {
    const notes = await complete(
      EXPERT_MODELS.reasoning,
      [
        { role: 'system', content: VERIFICATION_SYSTEM },
        {
          role: 'user',
          content: `Audit these expert outputs:\n\n${summary}`,
        },
      ],
      { maxTokens: 300, temperature: 0.1 }
    );
    return notes;
  } catch (err) {
    return `VERIFICATION SKIPPED: ${err instanceof Error ? err.message : String(err)}`;
  }
}
